# Generated by Django 3.2.4 on 2021-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('code', models.TextField()),
                ('verdict', models.CharField(max_length=12)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Checked',
        ),
        migrations.DeleteModel(
            name='Submit',
        ),
        migrations.AddField(
            model_name='question',
            name='input',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
